

  services:
    mongo:
      image: mongo
      container_name: mongodb
      ports:
        - "27018:27017"
      volumes:
        - mongo_data:/data/db

    backend:
      build: ./backend
      ports:
        - "5001:5000"
      env_file:
        - ./backend/.env
      depends_on:
        - mongo

    frontend:
      build: ./todo
      ports:
        - "3000:3000"
      environment:
        - NEXT_PUBLIC_API_URL=http://backend:5000
      depends_on:
        - backend

  volumes:
    mongo_data:
  